name: Python CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install system dependencies
      run: sudo apt update && sudo apt install -y python-pytest

    - name: Install dependencies
      # run: pip install -r requirements.txt
      run: sudo pip install -U requests && sudo pip install -U pytest pytest-html

    - name: Run tests
      run: pytest

    # - name: Commit changes
    #   run: git commit -am "Passed tests"

    - name: Push changes
      uses: ad-m/github-push-action@dev
      with:
        github_token: ${{ secrets.MY_TOKEN }}